"""CONTRAINTE

Revision ID: 790fce4ad8ee
Revises: 0b6a7f9741f3
Create Date: 2026-03-12 18:19:12.044753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790fce4ad8ee'
down_revision: Union[str, Sequence[str], None] = '0b6a7f9741f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
