services:
  - type: web
    name: gabon-culture-urbaine-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT